- project:
    templates:
      - openstack-python-jobs-neutron
      - publish-openstack-sphinx-docs
      - check-requirements
      - openstack-python35-jobs-neutron
    check:
      jobs:
        - networking-ovn-tempest-dsvm-ovs-release
        - networking-ovn-tempest-dsvm-ovs-release-python3
        - networking-ovn-dsvm-functional-py27
        - networking-ovn-dsvm-functional:
            branches: ^(?!stable/newton).*$
        # TripleO jobs that deploy OVN.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # tripleo-ci-centos-7-scenario007-multinode-oooq-container will
        # run in Pike and beyond.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
        - tripleo-ci-centos-7-scenario007-multinode-oooq-container:
            voting: false
        - networking-ovn-dsvm-grenade:
            branches: ^(?!stable/(ocata|pike|queens)).*$
            voting: false
        - openstack-tox-cover:
            required-projects:
              - openstack/neutron
            voting: false
    gate:
      jobs:
        - networking-ovn-tempest-dsvm-ovs-release
        - networking-ovn-tempest-dsvm-ovs-release-python3
        - networking-ovn-dsvm-functional-py27
        - networking-ovn-dsvm-functional:
            branches: ^(?!stable/newton).*$
        - tripleo-ci-centos-7-scenario007-multinode-oooq
    experimental:
      jobs:
        - networking-ovn-tempest-dsvm-multinode:
            voting: false
            branches: ^(?!stable/newton).*$
        - kuryr-kubernetes-tempest-ovn

