- project:
    check:
      jobs:
        - networking-ovn-tempest-dsvm-ovs-master:
            voting: false
        - networking-ovn-tempest-dsvm-ovs-release
        - networking-ovn-rally-dsvm
        - networking-ovn-dsvm-functional
        - networking-ovn-dsvm-functional-py35:
            branches: ^(?!stable/newton).*$
        - networking-ovn-install-dsvm-kuryr
        - networking-ovn-tempest-dsvm-neutron-api-scenario-ovs-release:
            voting: false
        # TripleO jobs that deploy OVN.
        # Note we don't use a project-template here, so it's easier
        # to disable voting on one specific job if things go wrong.
        # tripleo-ci-centos-7-scenario007-multinode-oooq will only
        # run on stable/pike while the -container will run in Queens
        # and beyond.
        # If you need any support to debug these jobs in case of
        # failures, please reach us on #tripleo IRC channel.
        - tripleo-ci-centos-7-scenario007-multinode-oooq
        - tripleo-ci-centos-7-scenario007-multinode-oooq-container
    gate:
      jobs:
        - networking-ovn-tempest-dsvm-ovs-release
        - networking-ovn-rally-dsvm
        - networking-ovn-dsvm-functional
        - networking-ovn-dsvm-functional-py35:
            branches: ^(?!stable/newton).*$
        - networking-ovn-install-dsvm-kuryr
        - tripleo-ci-centos-7-scenario007-multinode-oooq
        - tripleo-ci-centos-7-scenario007-multinode-oooq-container
    experimental:
      jobs:
        - networking-ovn-tempest-dsvm-ovs-master-python3:
            voting: false
        - networking-ovn-grenade-dsvm:
            voting: false
            branches: ^(?!(driverfixes|stable/(mitaka|newton))).*$
        - networking-ovn-tempest-dsvm-multinode:
            voting: false
            branches: ^(?!stable/newton).*$
