- project:
    templates:
      - openstack-python-jobs-neutron
      - publish-openstack-docs-pti
      - check-requirements
      - openstack-python35-jobs-neutron
      - openstack-python36-jobs-neutron
      - openstack-python37-jobs-neutron
    check:
      jobs:
        - networking-ovn-tempest-dsvm-ovs-release
        - networking-ovn-tempest-dsvm-ovs-release-python2
        - networking-ovn-rally-task
        - networking-ovn-dsvm-functional-py27
        - networking-ovn-dsvm-functional:
            branches: ^(?!stable/newton).*$
    gate:
      jobs:
        - networking-ovn-tempest-dsvm-ovs-release
        - networking-ovn-tempest-dsvm-ovs-release-python2
        - networking-ovn-rally-task
        - networking-ovn-dsvm-functional-py27
        - networking-ovn-dsvm-functional:
            branches: ^(?!stable/newton).*$
    experimental:
      jobs:
        - networking-ovn-tempest-dsvm-multinode:
            voting: false
            branches: ^(?!stable/newton).*$
        - kuryr-kubernetes-tempest-ovn
        - networking-ovn-dsvm-grenade:
            branches: ^(?!stable/(ocata|pike|queens)).*$
            voting: false
        - openstack-tox-cover:
            required-projects:
              - openstack/neutron
            voting: false
